# Codecov — https://app.codecov.io/gh/oramirez1512-CO/product-checkout-fe
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: 'header, diff, flags, files'
  behavior: default
  require_changes: false
